spring:
  social:
    kakao:
      client_id: ${KAKAO_CLIENT_ID}
      redirect: https://guiderun.org/oauth
      url:
        login: https://kauth.kakao.com/oauth/authorize  # 로그인 진행 사이트
        token: https://kauth.kakao.com/oauth/token  # access token을 발급 받는  url , 필요한 정보를 담아 보내야 함
        profile: https://kapi.kakao.com/v2/user/me  # Access Token을 통해 정보를 받는 url
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MAIN_RDS}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
cors:
  origin: https://guiderun.org